-- Inventory management for the car accessory shop.

-- Product categories (shared by all users of the shop).
create table "public"."categories" (
    "id" bigint generated by default as identity primary key,
    "name" text not null unique,
    "sort_order" integer not null default 0,
    "created_at" timestamptz not null default now()
);

insert into "public"."categories" ("name", "sort_order") values
    ('Android', 1),
    ('Camera', 2),
    ('Horn', 3),
    ('LED Headlights', 4),
    ('Fog Lights', 5),
    ('Single DIN', 6),
    ('Speakers', 7);

-- Products held in stock.
create table "public"."products" (
    "id" uuid not null default gen_random_uuid() primary key,
    "user_id" uuid not null default auth.uid() references auth.users(id) on delete cascade,
    "category_id" bigint not null references public.categories(id) on delete restrict,
    "name" text not null check (char_length(name) > 0),
    "brand" text,
    "model" text,
    "sku" text,
    "purchase_price" numeric(12, 2) not null default 0 check (purchase_price >= 0),
    "selling_price" numeric(12, 2) not null default 0 check (selling_price >= 0),
    "quantity" integer not null default 0 check (quantity >= 0),
    "reorder_level" integer not null default 5 check (reorder_level >= 0),
    "notes" text,
    "created_at" timestamptz not null default now(),
    "updated_at" timestamptz not null default now()
);

create index products_user_id_idx on public.products (user_id);
create index products_category_id_idx on public.products (category_id);
create unique index products_user_sku_idx on public.products (user_id, sku) where sku is not null;

-- Every change in stock level is recorded here.
create table "public"."stock_movements" (
    "id" bigint generated by default as identity primary key,
    "user_id" uuid not null default auth.uid() references auth.users(id) on delete cascade,
    "product_id" uuid not null references public.products(id) on delete cascade,
    "type" text not null check (type in ('in', 'out', 'adjust')),
    -- Signed change in quantity: positive for stock in, negative for sales.
    "quantity_change" integer not null,
    "quantity_after" integer not null,
    "unit_price" numeric(12, 2),
    "note" text,
    "created_at" timestamptz not null default now()
);

create index stock_movements_product_id_idx on public.stock_movements (product_id, created_at desc);
create index stock_movements_user_id_idx on public.stock_movements (user_id, created_at desc);

-- Keep updated_at fresh.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger products_set_updated_at
before update on public.products
for each row execute function public.set_updated_at();

-- Atomically change stock and log the movement.
--   type 'in'     : quantity is the number of units received (> 0)
--   type 'out'    : quantity is the number of units sold/removed (> 0)
--   type 'adjust' : quantity is the new counted stock level (>= 0)
create or replace function public.record_stock_movement(
  p_product_id uuid,
  p_type text,
  p_quantity integer,
  p_unit_price numeric default null,
  p_note text default null
)
returns public.products
language plpgsql
security invoker
as $$
declare
  current_qty integer;
  new_qty integer;
  result public.products;
begin
  if p_type not in ('in', 'out', 'adjust') then
    raise exception 'Invalid movement type: %', p_type;
  end if;

  if p_quantity is null or p_quantity < 0 or (p_type <> 'adjust' and p_quantity = 0) then
    raise exception 'Quantity must be greater than zero';
  end if;

  select quantity into current_qty
  from public.products
  where id = p_product_id
  for update;

  if not found then
    raise exception 'Product not found';
  end if;

  new_qty := case p_type
    when 'in' then current_qty + p_quantity
    when 'out' then current_qty - p_quantity
    else p_quantity
  end;

  if new_qty < 0 then
    raise exception 'Not enough stock: only % available', current_qty;
  end if;

  update public.products
  set quantity = new_qty
  where id = p_product_id
  returning * into result;

  insert into public.stock_movements
    (product_id, type, quantity_change, quantity_after, unit_price, note)
  values
    (p_product_id, p_type, new_qty - current_qty, new_qty, p_unit_price, p_note);

  return result;
end;
$$;

-- RLS
alter table "public"."categories" enable row level security;
alter table "public"."products" enable row level security;
alter table "public"."stock_movements" enable row level security;

create policy "Authenticated users can read categories"
on "public"."categories"
as permissive
for select
to authenticated
using (true);

create policy "Allow full access to own products"
on "public"."products"
as permissive
for all
to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));

create policy "Allow full access to own stock movements"
on "public"."stock_movements"
as permissive
for all
to authenticated
using ((auth.uid() = user_id))
with check ((auth.uid() = user_id));
