-- Car shop app: one shop shared by the owner and their staff.
--
-- * People get in by email: the first person to claim the shop becomes the
--   owner, and the owner adds staff emails in Settings.
-- * Buying prices and profit live in owner-only tables, so staff can never
--   read them, not even through the API.
-- * Stock and bills change only through the functions below, so every stock
--   change is logged and a sale can never take stock below zero.

-- ---------------------------------------------------------------------------
-- Who is who
-- ---------------------------------------------------------------------------

create table public.shop_members (
  email text primary key check (email = lower(email) and position('@' in email) > 1),
  role text not null check (role in ('owner', 'staff')),
  name text not null default '',
  created_at timestamptz not null default now()
);

-- Only one owner per shop.
create unique index shop_members_single_owner on public.shop_members (role) where role = 'owner';

create function public.shop_email()
returns text
language sql
stable
as $$
  select lower(coalesce(auth.jwt() ->> 'email', ''))
$$;

create function public.shop_is_member()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.shop_members where email = public.shop_email())
$$;

create function public.shop_is_owner()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.shop_members
    where email = public.shop_email() and role = 'owner'
  )
$$;

-- What the app needs to know about the signed-in person.
create function public.shop_me()
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  select jsonb_build_object(
    'email', public.shop_email(),
    'role', (select role from public.shop_members where email = public.shop_email()),
    'has_owner', exists (select 1 from public.shop_members where role = 'owner')
  )
$$;

-- The very first person to open a new shop makes themselves the owner.
create function public.shop_claim_owner()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null or public.shop_email() = '' then
    raise exception 'Please sign in first';
  end if;
  if exists (select 1 from public.shop_members where role = 'owner') then
    raise exception 'This shop already has an owner';
  end if;
  insert into public.shop_members (email, role)
  values (public.shop_email(), 'owner')
  on conflict (email) do update set role = 'owner';
end;
$$;

-- ---------------------------------------------------------------------------
-- Shop details and categories
-- ---------------------------------------------------------------------------

create table public.shop_settings (
  id integer primary key default 1 check (id = 1),
  name text not null default 'My Car Shop',
  address text not null default '',
  phone text not null default '',
  owner_whatsapp text not null default '',
  summary_time text not null default '21:00'
);

insert into public.shop_settings (id) values (1);

create table public.shop_categories (
  id bigint generated by default as identity primary key,
  name text not null unique check (char_length(trim(name)) > 0),
  sort_order integer not null default 0
);

insert into public.shop_categories (name, sort_order) values
  ('Android', 1),
  ('Camera', 2),
  ('Horn', 3),
  ('LED Headlights', 4),
  ('Fog Lights', 5),
  ('Single DIN', 6),
  ('Speakers', 7);

-- ---------------------------------------------------------------------------
-- Products, buying prices and stock history
-- ---------------------------------------------------------------------------

create table public.shop_products (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) > 0),
  category_id bigint references public.shop_categories (id) on delete set null,
  brand text not null default '',
  code text not null default '',
  price numeric(12, 2) not null default 0 check (price >= 0),
  qty integer not null default 0 check (qty >= 0),
  reorder_level integer not null default 3 check (reorder_level >= 0),
  warranty_months integer not null default 0 check (warranty_months >= 0),
  fits text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create unique index shop_products_code on public.shop_products (lower(code)) where code <> '' and active;

-- Owner only.
create table public.shop_product_costs (
  product_id uuid primary key references public.shop_products (id) on delete cascade,
  cost numeric(12, 2) not null default 0 check (cost >= 0),
  updated_at timestamptz not null default now()
);

-- Owner only.
create table public.shop_cost_history (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.shop_products (id) on delete cascade,
  cost numeric(12, 2) not null,
  created_at timestamptz not null default now()
);

create table public.shop_stock_moves (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.shop_products (id) on delete cascade,
  created_at timestamptz not null default now(),
  kind text not null check (kind in ('opening', 'sale', 'delivery', 'count', 'return', 'damaged', 'cancel')),
  change integer not null,
  qty_after integer not null,
  note text not null default '',
  created_by text not null default public.shop_email()
);

create index shop_stock_moves_product on public.shop_stock_moves (product_id, created_at desc);
create index shop_stock_moves_time on public.shop_stock_moves (created_at);

-- ---------------------------------------------------------------------------
-- Customers, fitting jobs and quotations
-- ---------------------------------------------------------------------------

create table public.shop_customers (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) > 0),
  phone text not null default '',
  -- [{ "no": "KL-07-AB-1234", "model": "Swift" }]
  cars jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table public.shop_jobs (
  id uuid primary key default gen_random_uuid(),
  no bigint generated by default as identity (start with 301) unique,
  created_at timestamptz not null default now(),
  customer_id uuid references public.shop_customers (id) on delete set null,
  car_no text not null default '',
  model text not null default '',
  work text not null default '',
  tech text not null default '',
  labour numeric(12, 2) not null default 0 check (labour >= 0),
  status text not null default 'waiting' check (status in ('waiting', 'working', 'ready', 'billed')),
  created_by text not null default public.shop_email()
);

create table public.shop_quotes (
  id uuid primary key default gen_random_uuid(),
  no bigint generated by default as identity (start with 201) unique,
  created_at timestamptz not null default now(),
  customer_id uuid references public.shop_customers (id) on delete set null,
  -- [{ "product_id": "...", "name": "...", "qty": 1, "price": 1500 }]
  items jsonb not null default '[]'::jsonb,
  total numeric(12, 2) not null default 0 check (total >= 0),
  status text not null default 'open' check (status in ('open', 'billed')),
  created_by text not null default public.shop_email()
);

-- ---------------------------------------------------------------------------
-- Bills and udhaar
-- ---------------------------------------------------------------------------

create table public.shop_bills (
  id uuid primary key default gen_random_uuid(),
  no bigint generated by default as identity (start with 1001) unique,
  created_at timestamptz not null default now(),
  customer_id uuid references public.shop_customers (id) on delete set null,
  total numeric(12, 2) not null check (total >= 0),
  paid_cash numeric(12, 2) not null default 0 check (paid_cash >= 0),
  paid_upi numeric(12, 2) not null default 0 check (paid_upi >= 0),
  paid_card numeric(12, 2) not null default 0 check (paid_card >= 0),
  -- What the customer still owes on this bill (udhaar).
  due numeric(12, 2) not null default 0 check (due >= 0),
  job_id uuid references public.shop_jobs (id) on delete set null,
  quote_id uuid references public.shop_quotes (id) on delete set null,
  cancelled boolean not null default false,
  created_by text not null default public.shop_email()
);

create index shop_bills_time on public.shop_bills (created_at desc);
create index shop_bills_customer on public.shop_bills (customer_id);

create table public.shop_bill_items (
  id bigint generated by default as identity primary key,
  bill_id uuid not null references public.shop_bills (id) on delete cascade,
  -- Empty for fitting charges and other services.
  product_id uuid references public.shop_products (id) on delete set null,
  name text not null,
  qty integer not null check (qty > 0),
  price numeric(12, 2) not null check (price >= 0),
  warranty_months integer not null default 0,
  serial text not null default ''
);

create index shop_bill_items_bill on public.shop_bill_items (bill_id);
create index shop_bill_items_product on public.shop_bill_items (product_id);

-- Owner only: the buying price of each sold item at the time of sale.
create table public.shop_bill_item_costs (
  item_id bigint primary key references public.shop_bill_items (id) on delete cascade,
  cost numeric(12, 2) not null default 0
);

-- Udhaar money received later.
create table public.shop_payments (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  customer_id uuid not null references public.shop_customers (id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  mode text not null check (mode in ('cash', 'upi', 'card')),
  created_by text not null default public.shop_email()
);

create index shop_payments_customer on public.shop_payments (customer_id);
create index shop_payments_time on public.shop_payments (created_at);

-- ---------------------------------------------------------------------------
-- Owner only: suppliers, purchases and expenses
-- ---------------------------------------------------------------------------

create table public.shop_suppliers (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(trim(name)) > 0),
  phone text not null default '',
  created_at timestamptz not null default now()
);

create table public.shop_purchases (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  supplier_id uuid not null references public.shop_suppliers (id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  paid numeric(12, 2) not null default 0 check (paid >= 0 and paid <= amount),
  mode text not null default 'upi' check (mode in ('cash', 'upi', 'card')),
  note text not null default ''
);

create table public.shop_supplier_payments (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  supplier_id uuid not null references public.shop_suppliers (id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  mode text not null check (mode in ('cash', 'upi', 'card'))
);

create table public.shop_expenses (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default now(),
  category text not null check (char_length(trim(category)) > 0),
  amount numeric(12, 2) not null check (amount > 0),
  mode text not null check (mode in ('cash', 'upi', 'card')),
  note text not null default ''
);

create index shop_expenses_time on public.shop_expenses (created_at);

-- ---------------------------------------------------------------------------
-- Money owed, per customer and per supplier
-- ---------------------------------------------------------------------------

create view public.shop_customer_dues with (security_invoker = true) as
select
  c.id as customer_id,
  coalesce(b.due, 0) - coalesce(p.paid, 0) as due,
  b.oldest_unpaid
from public.shop_customers c
left join (
  select customer_id, sum(due) as due, min(created_at) filter (where due > 0) as oldest_unpaid
  from public.shop_bills
  where not cancelled
  group by customer_id
) b on b.customer_id = c.id
left join (
  select customer_id, sum(amount) as paid
  from public.shop_payments
  group by customer_id
) p on p.customer_id = c.id;

create view public.shop_supplier_dues with (security_invoker = true) as
select
  s.id as supplier_id,
  coalesce(pu.total, 0) as purchased,
  coalesce(pu.unpaid, 0) - coalesce(sp.paid, 0) as owed
from public.shop_suppliers s
left join (
  select supplier_id, sum(amount) as total, sum(amount - paid) as unpaid
  from public.shop_purchases
  group by supplier_id
) pu on pu.supplier_id = s.id
left join (
  select supplier_id, sum(amount) as paid
  from public.shop_supplier_payments
  group by supplier_id
) sp on sp.supplier_id = s.id;

-- ---------------------------------------------------------------------------
-- Stock functions
-- ---------------------------------------------------------------------------

create function public.shop_set_cost(p_product uuid, p_cost numeric)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.shop_is_owner() then
    raise exception 'Only the owner can set buying prices';
  end if;
  if p_cost is null or p_cost < 0 then
    raise exception 'Buying price cannot be negative';
  end if;
  if exists (select 1 from public.shop_product_costs where product_id = p_product and cost = p_cost) then
    return;
  end if;
  insert into public.shop_product_costs (product_id, cost, updated_at)
  values (p_product, p_cost, now())
  on conflict (product_id) do update set cost = excluded.cost, updated_at = now();
  insert into public.shop_cost_history (product_id, cost) values (p_product, p_cost);
end;
$$;

-- Add a new product (no "id") or edit one. "qty" is only used for new products;
-- "cost" is only saved when the owner sends it.
create function public.shop_save_product(p jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid := nullif(p ->> 'id', '')::uuid;
  v_qty integer := greatest(0, coalesce(nullif(p ->> 'qty', '')::integer, 0));
begin
  if not public.shop_is_member() then
    raise exception 'You are not part of this shop';
  end if;
  if coalesce(trim(p ->> 'name'), '') = '' then
    raise exception 'Product name is needed';
  end if;

  if v_id is null then
    insert into public.shop_products (name, category_id, brand, code, price, qty, reorder_level, warranty_months, fits)
    values (
      trim(p ->> 'name'),
      nullif(p ->> 'category_id', '')::bigint,
      coalesce(trim(p ->> 'brand'), ''),
      coalesce(trim(p ->> 'code'), ''),
      coalesce(nullif(p ->> 'price', '')::numeric, 0),
      v_qty,
      coalesce(nullif(p ->> 'reorder_level', '')::integer, 3),
      coalesce(nullif(p ->> 'warranty_months', '')::integer, 0),
      coalesce(trim(p ->> 'fits'), '')
    )
    returning id into v_id;
    insert into public.shop_stock_moves (product_id, kind, change, qty_after, note)
    values (v_id, 'opening', v_qty, v_qty, coalesce(p ->> 'note', ''));
  else
    update public.shop_products set
      name = trim(p ->> 'name'),
      category_id = nullif(p ->> 'category_id', '')::bigint,
      brand = coalesce(trim(p ->> 'brand'), ''),
      code = coalesce(trim(p ->> 'code'), ''),
      price = coalesce(nullif(p ->> 'price', '')::numeric, 0),
      reorder_level = coalesce(nullif(p ->> 'reorder_level', '')::integer, 3),
      warranty_months = coalesce(nullif(p ->> 'warranty_months', '')::integer, 0),
      fits = coalesce(trim(p ->> 'fits'), '')
    where id = v_id and active;
    if not found then
      raise exception 'Product not found';
    end if;
  end if;

  if public.shop_is_owner() and nullif(p ->> 'cost', '') is not null then
    perform public.shop_set_cost(v_id, (p ->> 'cost')::numeric);
  end if;

  return v_id;
end;
$$;

-- Bulk add: a list of new products in one go.
create function public.shop_add_products(p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  r jsonb;
  n integer := 0;
begin
  if jsonb_typeof(p_rows) is distinct from 'array' then
    raise exception 'Expected a list of products';
  end if;
  for r in select * from jsonb_array_elements(p_rows) loop
    perform public.shop_save_product(r - 'id');
    n := n + 1;
  end loop;
  return n;
end;
$$;

-- Hide a product (owner only). Old bills keep their history.
create function public.shop_delete_product(p_product uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.shop_is_owner() then
    raise exception 'Only the owner can delete products';
  end if;
  update public.shop_products set active = false where id = p_product;
end;
$$;

--   delivery / return : add p_qty
--   damaged           : remove p_qty
--   count             : set stock to p_qty
create function public.shop_adjust_stock(p_product uuid, p_kind text, p_qty integer, p_note text default '')
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  cur integer;
  nxt integer;
begin
  if not public.shop_is_member() then
    raise exception 'You are not part of this shop';
  end if;
  if p_kind not in ('delivery', 'count', 'return', 'damaged') then
    raise exception 'Unknown stock change: %', p_kind;
  end if;
  if p_qty is null or p_qty < 0 or (p_kind <> 'count' and p_qty = 0) then
    raise exception 'Type a quantity';
  end if;

  select qty into cur from public.shop_products where id = p_product and active for update;
  if not found then
    raise exception 'Product not found';
  end if;

  nxt := case p_kind
    when 'count' then p_qty
    when 'damaged' then greatest(0, cur - p_qty)
    else cur + p_qty
  end;

  update public.shop_products set qty = nxt where id = p_product;
  insert into public.shop_stock_moves (product_id, kind, change, qty_after, note)
  values (p_product, p_kind, nxt - cur, nxt, coalesce(p_note, ''));
  return nxt;
end;
$$;

-- Bulk "add quantity": [{ "product_id": "...", "qty": 10, "cost": 1400 }]
create function public.shop_receive_stock(p_rows jsonb)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  r jsonb;
  q integer;
  total integer := 0;
begin
  if jsonb_typeof(p_rows) is distinct from 'array' then
    raise exception 'Expected a list of products';
  end if;
  for r in select * from jsonb_array_elements(p_rows) loop
    q := nullif(r ->> 'qty', '')::integer;
    if q is null or q <= 0 then
      continue;
    end if;
    perform public.shop_adjust_stock((r ->> 'product_id')::uuid, 'delivery', q, coalesce(r ->> 'note', ''));
    if public.shop_is_owner() and nullif(r ->> 'cost', '') is not null then
      perform public.shop_set_cost((r ->> 'product_id')::uuid, (r ->> 'cost')::numeric);
    end if;
    total := total + q;
  end loop;
  if total = 0 then
    raise exception 'Type how many arrived';
  end if;
  return total;
end;
$$;

-- ---------------------------------------------------------------------------
-- Bills
-- ---------------------------------------------------------------------------

-- {
--   "customer_id": "...", "cash": 0, "upi": 7198, "card": 0,
--   "job_id": "...", "quote_id": "...",
--   "items": [{ "product_id": "...", "name": "...", "qty": 1, "price": 5499, "serial": "" }]
-- }
create function public.shop_create_bill(p jsonb)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bill uuid;
  v_no bigint;
  v_total numeric := 0;
  v_cash numeric := greatest(0, coalesce(nullif(p ->> 'cash', '')::numeric, 0));
  v_upi numeric := greatest(0, coalesce(nullif(p ->> 'upi', '')::numeric, 0));
  v_card numeric := greatest(0, coalesce(nullif(p ->> 'card', '')::numeric, 0));
  v_customer uuid := nullif(p ->> 'customer_id', '')::uuid;
  v_job uuid := nullif(p ->> 'job_id', '')::uuid;
  v_quote uuid := nullif(p ->> 'quote_id', '')::uuid;
  it jsonb;
  v_pid uuid;
  v_qty integer;
  v_price numeric;
  v_name text;
  v_warranty integer;
  v_stock integer;
  v_item bigint;
begin
  if not public.shop_is_member() then
    raise exception 'You are not part of this shop';
  end if;
  if jsonb_typeof(p -> 'items') is distinct from 'array' or jsonb_array_length(p -> 'items') = 0 then
    raise exception 'Add at least one item';
  end if;

  for it in select * from jsonb_array_elements(p -> 'items') loop
    v_qty := nullif(it ->> 'qty', '')::integer;
    v_price := nullif(it ->> 'price', '')::numeric;
    if v_qty is null or v_qty < 1 then
      raise exception 'Quantity must be at least 1';
    end if;
    if v_price is null or v_price < 0 then
      raise exception 'Price cannot be negative';
    end if;
    v_total := v_total + v_qty * v_price;
  end loop;

  if v_cash + v_upi + v_card > v_total then
    raise exception 'Paid amount is more than the bill total';
  end if;
  if v_total - (v_cash + v_upi + v_card) > 0 and v_customer is null then
    raise exception 'Choose a customer for udhaar';
  end if;

  insert into public.shop_bills (customer_id, total, paid_cash, paid_upi, paid_card, due, job_id, quote_id)
  values (v_customer, v_total, v_cash, v_upi, v_card, v_total - (v_cash + v_upi + v_card), v_job, v_quote)
  returning id, no into v_bill, v_no;

  for it in select * from jsonb_array_elements(p -> 'items') loop
    v_pid := nullif(it ->> 'product_id', '')::uuid;
    v_qty := (it ->> 'qty')::integer;
    v_price := (it ->> 'price')::numeric;
    v_name := coalesce(nullif(trim(it ->> 'name'), ''), 'Item');
    v_warranty := 0;

    if v_pid is not null then
      select qty, name, warranty_months into v_stock, v_name, v_warranty
      from public.shop_products
      where id = v_pid and active
      for update;
      if not found then
        raise exception 'A product in this bill no longer exists';
      end if;
      if v_stock < v_qty then
        raise exception 'Only % of % in stock', v_stock, v_name;
      end if;
      update public.shop_products set qty = v_stock - v_qty where id = v_pid;
      insert into public.shop_stock_moves (product_id, kind, change, qty_after, note)
      values (v_pid, 'sale', -v_qty, v_stock - v_qty, 'Bill B-' || v_no);
    end if;

    insert into public.shop_bill_items (bill_id, product_id, name, qty, price, warranty_months, serial)
    values (v_bill, v_pid, v_name, v_qty, v_price, coalesce(v_warranty, 0), coalesce(trim(it ->> 'serial'), ''))
    returning id into v_item;

    insert into public.shop_bill_item_costs (item_id, cost)
    values (v_item, coalesce((select cost from public.shop_product_costs where product_id = v_pid), 0));
  end loop;

  if v_job is not null then
    update public.shop_jobs set status = 'billed' where id = v_job;
  end if;
  if v_quote is not null then
    update public.shop_quotes set status = 'billed' where id = v_quote;
  end if;

  return v_bill;
end;
$$;

-- Owner only: cancel a wrong bill and put its items back in stock.
create function public.shop_cancel_bill(p_bill uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  b public.shop_bills;
  it record;
  cur integer;
begin
  if not public.shop_is_owner() then
    raise exception 'Only the owner can cancel a bill';
  end if;
  select * into b from public.shop_bills where id = p_bill for update;
  if not found then
    raise exception 'Bill not found';
  end if;
  if b.cancelled then
    raise exception 'This bill is already cancelled';
  end if;

  for it in
    select product_id, qty from public.shop_bill_items
    where bill_id = p_bill and product_id is not null
  loop
    select qty into cur from public.shop_products where id = it.product_id for update;
    if found then
      update public.shop_products set qty = cur + it.qty where id = it.product_id;
      insert into public.shop_stock_moves (product_id, kind, change, qty_after, note)
      values (it.product_id, 'cancel', it.qty, cur + it.qty, 'Bill B-' || b.no || ' cancelled');
    end if;
  end loop;

  update public.shop_bills set cancelled = true where id = p_bill;
end;
$$;

-- ---------------------------------------------------------------------------
-- Owner reports
-- ---------------------------------------------------------------------------

-- Totals for [p_from, p_to). p_buckets are the start times of chart bars;
-- each bar runs until the next start (the last one until p_to).
create function public.shop_report(p_from timestamptz, p_to timestamptz, p_buckets timestamptz[] default '{}')
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  result jsonb;
begin
  if not public.shop_is_owner() then
    raise exception 'Only the owner can see reports';
  end if;

  with
  b as (
    select * from public.shop_bills
    where not cancelled and created_at >= p_from and created_at < p_to
  ),
  it as (
    select i.product_id, i.name, i.qty, i.price, coalesce(c.cost, 0) as cost
    from public.shop_bill_items i
    join b on b.id = i.bill_id
    left join public.shop_bill_item_costs c on c.item_id = i.id
  ),
  pay as (
    select * from public.shop_payments where created_at >= p_from and created_at < p_to
  ),
  ex as (
    select * from public.shop_expenses where created_at >= p_from and created_at < p_to
  ),
  pur as (
    select * from public.shop_purchases where created_at >= p_from and created_at < p_to
  ),
  sp as (
    select * from public.shop_supplier_payments where created_at >= p_from and created_at < p_to
  ),
  modes as (
    select m.mode,
      coalesce((select sum(case m.mode when 'cash' then paid_cash when 'upi' then paid_upi else paid_card end) from b), 0)
      + coalesce((select sum(amount) from pay where pay.mode = m.mode), 0)
      - coalesce((select sum(amount) from ex where ex.mode = m.mode), 0)
      - coalesce((select sum(paid) from pur where pur.mode = m.mode), 0)
      - coalesce((select sum(amount) from sp where sp.mode = m.mode), 0) as net
    from (values ('cash'), ('upi'), ('card')) as m(mode)
  ),
  per_product as (
    select
      it.product_id,
      coalesce(max(pr.name), max(it.name)) as name,
      max(c.name) as category,
      sum(it.qty) as qty,
      sum(it.qty * it.price) as sales,
      sum(it.qty * (it.price - it.cost)) as profit
    from it
    left join public.shop_products pr on pr.id = it.product_id
    left join public.shop_categories c on c.id = pr.category_id
    group by it.product_id
  )
  select jsonb_build_object(
    'sales', coalesce((select sum(total) from b), 0),
    'bills', (select count(*) from b),
    'cash', coalesce((select sum(paid_cash) from b), 0),
    'upi', coalesce((select sum(paid_upi) from b), 0),
    'card', coalesce((select sum(paid_card) from b), 0),
    'later', coalesce((select sum(due) from b), 0),
    'items', coalesce((select sum(qty) from it where product_id is not null), 0),
    'profit', coalesce((select sum(qty * (price - cost)) from it), 0),
    'expenses', coalesce((select sum(amount) from ex), 0),
    'received', coalesce((select sum(amount) from pay), 0),
    'stock_in', coalesce((
      select sum(change) from public.shop_stock_moves
      where created_at >= p_from and created_at < p_to and kind in ('opening', 'delivery') and change > 0
    ), 0),
    'drawer', (select jsonb_object_agg(mode, net) from modes),
    'buckets', (
      select coalesce(jsonb_agg(coalesce(s.v, 0) order by g.i), '[]'::jsonb)
      from generate_subscripts(p_buckets, 1) as g(i)
      left join lateral (
        select sum(total) as v from b
        where created_at >= p_buckets[g.i] and created_at < coalesce(p_buckets[g.i + 1], p_to)
      ) s on true
    ),
    'products', (
      select coalesce(jsonb_agg(to_jsonb(x) order by x.profit desc), '[]'::jsonb)
      from per_product x
    )
  )
  into result;

  return result;
end;
$$;

-- ---------------------------------------------------------------------------
-- Row level security
-- ---------------------------------------------------------------------------

alter table public.shop_members enable row level security;
alter table public.shop_settings enable row level security;
alter table public.shop_categories enable row level security;
alter table public.shop_products enable row level security;
alter table public.shop_product_costs enable row level security;
alter table public.shop_cost_history enable row level security;
alter table public.shop_stock_moves enable row level security;
alter table public.shop_customers enable row level security;
alter table public.shop_jobs enable row level security;
alter table public.shop_quotes enable row level security;
alter table public.shop_bills enable row level security;
alter table public.shop_bill_items enable row level security;
alter table public.shop_bill_item_costs enable row level security;
alter table public.shop_payments enable row level security;
alter table public.shop_suppliers enable row level security;
alter table public.shop_purchases enable row level security;
alter table public.shop_supplier_payments enable row level security;
alter table public.shop_expenses enable row level security;

-- Team: owner manages staff.
create policy "Owner sees the team" on public.shop_members
  for select to authenticated using ((select public.shop_is_owner()));
create policy "Owner adds staff" on public.shop_members
  for insert to authenticated with check ((select public.shop_is_owner()) and role = 'staff');
create policy "Owner edits staff" on public.shop_members
  for update to authenticated using ((select public.shop_is_owner()) and role = 'staff') with check (role = 'staff');
create policy "Owner removes staff" on public.shop_members
  for delete to authenticated using ((select public.shop_is_owner()) and role = 'staff');

-- Shop details and categories: everyone reads, owner edits.
create policy "Team reads settings" on public.shop_settings
  for select to authenticated using ((select public.shop_is_member()));
create policy "Owner edits settings" on public.shop_settings
  for update to authenticated using ((select public.shop_is_owner())) with check ((select public.shop_is_owner()));

create policy "Team reads categories" on public.shop_categories
  for select to authenticated using ((select public.shop_is_member()));
create policy "Owner adds categories" on public.shop_categories
  for insert to authenticated with check ((select public.shop_is_owner()));
create policy "Owner edits categories" on public.shop_categories
  for update to authenticated using ((select public.shop_is_owner())) with check ((select public.shop_is_owner()));
create policy "Owner removes categories" on public.shop_categories
  for delete to authenticated using ((select public.shop_is_owner()));

-- Products, stock and bills: everyone reads; changes go through the functions.
create policy "Team reads products" on public.shop_products
  for select to authenticated using ((select public.shop_is_member()));
create policy "Team reads stock history" on public.shop_stock_moves
  for select to authenticated using ((select public.shop_is_member()));
create policy "Team reads bills" on public.shop_bills
  for select to authenticated using ((select public.shop_is_member()));
create policy "Team reads bill items" on public.shop_bill_items
  for select to authenticated using ((select public.shop_is_member()));

-- Buying prices: owner only.
create policy "Owner reads buying prices" on public.shop_product_costs
  for select to authenticated using ((select public.shop_is_owner()));
create policy "Owner reads buying price history" on public.shop_cost_history
  for select to authenticated using ((select public.shop_is_owner()));
create policy "Owner reads sold item costs" on public.shop_bill_item_costs
  for select to authenticated using ((select public.shop_is_owner()));

-- Customers, jobs, quotations and udhaar payments: the whole team works on them.
create policy "Team reads customers" on public.shop_customers
  for select to authenticated using ((select public.shop_is_member()));
create policy "Team adds customers" on public.shop_customers
  for insert to authenticated with check ((select public.shop_is_member()));
create policy "Team edits customers" on public.shop_customers
  for update to authenticated using ((select public.shop_is_member())) with check ((select public.shop_is_member()));
create policy "Owner removes customers" on public.shop_customers
  for delete to authenticated using ((select public.shop_is_owner()));

create policy "Team reads jobs" on public.shop_jobs
  for select to authenticated using ((select public.shop_is_member()));
create policy "Team adds jobs" on public.shop_jobs
  for insert to authenticated with check ((select public.shop_is_member()));
create policy "Team edits jobs" on public.shop_jobs
  for update to authenticated using ((select public.shop_is_member())) with check ((select public.shop_is_member()));
create policy "Owner removes jobs" on public.shop_jobs
  for delete to authenticated using ((select public.shop_is_owner()));

create policy "Team reads quotations" on public.shop_quotes
  for select to authenticated using ((select public.shop_is_member()));
create policy "Team adds quotations" on public.shop_quotes
  for insert to authenticated with check ((select public.shop_is_member()));
create policy "Team edits quotations" on public.shop_quotes
  for update to authenticated using ((select public.shop_is_member())) with check ((select public.shop_is_member()));
create policy "Owner removes quotations" on public.shop_quotes
  for delete to authenticated using ((select public.shop_is_owner()));

create policy "Team reads udhaar payments" on public.shop_payments
  for select to authenticated using ((select public.shop_is_member()));
create policy "Team records udhaar payments" on public.shop_payments
  for insert to authenticated with check ((select public.shop_is_member()));
create policy "Owner removes udhaar payments" on public.shop_payments
  for delete to authenticated using ((select public.shop_is_owner()));

-- Suppliers, purchases and expenses: owner only.
create policy "Owner manages suppliers" on public.shop_suppliers
  for all to authenticated using ((select public.shop_is_owner())) with check ((select public.shop_is_owner()));
create policy "Owner manages purchases" on public.shop_purchases
  for all to authenticated using ((select public.shop_is_owner())) with check ((select public.shop_is_owner()));
create policy "Owner manages supplier payments" on public.shop_supplier_payments
  for all to authenticated using ((select public.shop_is_owner())) with check ((select public.shop_is_owner()));
create policy "Owner manages expenses" on public.shop_expenses
  for all to authenticated using ((select public.shop_is_owner())) with check ((select public.shop_is_owner()));

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

grant select, insert, update, delete on
  public.shop_members,
  public.shop_settings,
  public.shop_categories,
  public.shop_products,
  public.shop_product_costs,
  public.shop_cost_history,
  public.shop_stock_moves,
  public.shop_customers,
  public.shop_jobs,
  public.shop_quotes,
  public.shop_bills,
  public.shop_bill_items,
  public.shop_bill_item_costs,
  public.shop_payments,
  public.shop_suppliers,
  public.shop_purchases,
  public.shop_supplier_payments,
  public.shop_expenses
to authenticated;

grant select on public.shop_customer_dues, public.shop_supplier_dues to authenticated;

revoke execute on function
  public.shop_me(),
  public.shop_claim_owner(),
  public.shop_set_cost(uuid, numeric),
  public.shop_save_product(jsonb),
  public.shop_add_products(jsonb),
  public.shop_delete_product(uuid),
  public.shop_adjust_stock(uuid, text, integer, text),
  public.shop_receive_stock(jsonb),
  public.shop_create_bill(jsonb),
  public.shop_cancel_bill(uuid),
  public.shop_report(timestamptz, timestamptz, timestamptz[])
from public, anon;

grant execute on function
  public.shop_me(),
  public.shop_claim_owner(),
  public.shop_set_cost(uuid, numeric),
  public.shop_save_product(jsonb),
  public.shop_add_products(jsonb),
  public.shop_delete_product(uuid),
  public.shop_adjust_stock(uuid, text, integer, text),
  public.shop_receive_stock(jsonb),
  public.shop_create_bill(jsonb),
  public.shop_cancel_bill(uuid),
  public.shop_report(timestamptz, timestamptz, timestamptz[])
to authenticated;
